// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY79eJFBnw-NCnDPCSI1zL-eIMPDogd3A',
    appId: '1:220838542476:web:e45d9a370213b107068fa9',
    messagingSenderId: '220838542476',
    projectId: 'irrigation-813bc',
    authDomain: 'irrigation-813bc.firebaseapp.com',
    storageBucket: 'irrigation-813bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF7fvhWrpAvI9kaUCE__rdCHfiUGMZfsk',
    appId: '1:220838542476:android:0017a73ebb245ae4068fa9',
    messagingSenderId: '220838542476',
    projectId: 'irrigation-813bc',
    storageBucket: 'irrigation-813bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8PWp0HH3XdDkho0xO5TePhrkVamOkMME',
    appId: '1:220838542476:ios:37d3cfd191207402068fa9',
    messagingSenderId: '220838542476',
    projectId: 'irrigation-813bc',
    storageBucket: 'irrigation-813bc.appspot.com',
    iosBundleId: 'com.example.irrigation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8PWp0HH3XdDkho0xO5TePhrkVamOkMME',
    appId: '1:220838542476:ios:12eb969f330ab2fb068fa9',
    messagingSenderId: '220838542476',
    projectId: 'irrigation-813bc',
    storageBucket: 'irrigation-813bc.appspot.com',
    iosBundleId: 'com.example.irrigation.RunnerTests',
  );
}
